name: mscred
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cudatoolkit=11.7
  - numpy=1.21.6
  - scikit-learn=0.24.2
  - pandas=1.3.5
  - matplotlib=3.2.0
  - h5py=3.4.0
  - pip
  - pip:
      - tqdm==4.62.2
